spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:
  application: dev
    name: microsoftcloud-config-eureka
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己,eureka自己无需注册自己。服务端才需要注册到注册中心，即微服务工程
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去获取已经注册的服务，不必获取eureka是否有在注册中心，
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
spring:
  profiles:
  application: test
    name: microsoftcloud-config-eureka
server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己,eureka自己无需注册自己。服务端才需要注册到注册中心，即微服务工程
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去获取已经注册的服务，不必获取eureka是否有在注册中心，
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/